platform :osx
link_with 'GDJson', 'GDJsonTests'

# pod 'J2ObjC', :git => 'https://github.com/goodow/j2objc.git'
# pod 'J2ObjC', :path => '~/dev/tools/lib/j2objc/J2ObjC.podspec'

pod 'GDJson', :path => '..'
# Next line needs to manually import generated sources to Xcode.
# podspec :path => '../GDJson.podspec'

#target :GDJsonTests, :exclusive => false do
#  platform :osx
#  pod 'GDJson', :path => '..'
#end
